fix: add dependencies on aws_guardduty_organization_admin_account
Error: error updating GuardDuty Organization Configuration (30b8ec9fec3882eded649f71872e1938): BadRequestException: The request failed because a delegated administrator account has not been enabled.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "c51102c5-a779-4ed8-a967-fe5f2948769c"
  },
  Message_: "The request failed because a delegated administrator account has not been enabled.",
  Type: "InvalidInputException"
}